name: meu_app
description: "App de Gestão Escolar com login GOV.BR"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5      # Abrir GOV.BR
  shared_preferences: ^2.2.2 # Salvar login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Gerar ícone automático

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png